name: CI on PR Back
on:
  pull_request:
    branches:
      - master
      - pre-prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Use Node.js  
        uses: actions/setup-node@v1  
        with:  
          node-version: '12.x'
      - name: Install dependecies
        run: npm install
        working-directory: backend
      - name: Build
        run: npm run build --if-present
        working-directory: Front
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          eslint: true
          eslint_args: "--fix"
          eslint_dir: backend
          prettier: true
          prettier_args: "-w"
          prettier_dir: backend